name: Go

on: [push, pull_request]

runs-on: ${{ matrix.os }}
strategy:
  matrix:
    os:
      - ubuntu-latest
      - ubuntu-16.04
      - macos-latest
    golang:
      - 1.13
      - 1.14
      - master

jobs:
  test:
    name: Test
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.golang }}
      id: go

    - uses: actions/checkout@v2

    - name: Run tests
      run: make ci
